### ISSUE TITLE
Question: How are these patched images prepared?

### ISSUE THREAD

**Issue by emory** [danielstuart14/ASUS_BIOS_REPO#1]
Are these essentially DSDT/SSDT edits and modifications cooked into the firmware images, or updated modules and binary blobs that are molded into a complete image?

(My Hac is a Z97 Gryphon and I've never had to unlock the MSR on mine but I know other people have had to with other models, I'm using Asus firmware presently with an SSDT-injected series of changes for remapping an HDAU device from RampageDev — I believe it also does some timing/performance changes as well.)

**Comment by danielstuart14** [comment]
These modifications were made with UBU + UefiTool.
So, the acpi tables are untouched. What I updated was the bios drivers.

**Comment by emory** [comment]
Got it — so new(er) microcode and AHCI/RAID code, etc? Thank you.

**Comment by danielstuart14** [comment]
yes

**Comment by ireun** [comment]
Also, if anyone would be interested what versions of drivers is used in these ROMs here they are.. It from P8Z77-V motherboard. ;)

![cmd_2017-03-14_10-59-51 2](https://cloud.githubusercontent.com/assets/695818/23897977/881fdd98-08af-11e7-985f-66cf7f435bab.png)
