### ISSUE TITLE
B85 NVME support?

### ISSUE THREAD

**Issue by wingedmy** [danielstuart14/ASUS_BIOS_REPO#10]
Is it posible about NVME support on B85 Pro gamer ?

**Comment by danielstuart14** [comment]
As said in the readme, only boards that I own will have an "advanced" bios.
But you can check how to add nvme here: https://www.win-raid.com/t871f16-Guide-How-to-get-full-NVMe-support-for-all-Systems-with-an-AMI-UEFI-BIOS.html
