### ISSUE TITLE
H61M-C (0511)

### ISSUE THREAD

**Issue by PunksterSanders** [danielstuart14/ASUS_BIOS_REPO#11]
Is it possible to have an updated, and EZ Flash 2 flashable .CAP for that motherboard? I haven't been able to mod it myself and update the GOP/OROM/Microcodes

I'm using UBU 1.69.5

**Comment by PunksterSanders** [comment]
Original
[img]https://i.imgur.com/DhzbNbf.jpg[/img]

What I'm trying to achieve
[img]https://i.imgur.com/SC317tb.jpg[/img]

**Comment by danielstuart14** [comment]
You are having trouble flashing it?

**Comment by PunksterSanders** [comment]
Yup, I'm trying to flash it within AFUDOS using the /GAN command, it seems to flash correctly, everything gets "done" but after I turn it off and on again to dump the actual bios and re-read it in UBU, it shows the original OROMs instead of the updated ones. If I try to do the flash within EZ Flash 2, I get a "Security Verification Failed", and if I try to do the AFUDOS /P /B /K command, it says something along the lines of "Can't write BIOS with secure protection" ... can't remember exactly the message. I'm a bit puzzled

**Comment by danielstuart14** [comment]
Yeah, you have an SMI locked bios, quite normal. There are some cases where /GAN doesn't work also, you can try with other version of AFU.

If you don't suceed, I'd recommend trying to update with an arduino. Check here: https://tomvanveen.eu/flashing-bios-chip-arduino/ (I recommend an original arduino, but a clone may work)
