### ISSUE TITLE
x299 bios

### ISSUE THREAD

**Issue by interferenc** [danielstuart14/ASUS_BIOS_REPO#12]
Hey there,

Nice repo! Any chance you can point me to the right direction to find out how to patch a Asus Strix X299 board for PM fix?

Thanks.

M

**Comment by danielstuart14** [comment]
1. Download UEFIpatch:
  win: https://github.com/LongSoft/UEFITool/releases/download/0.21.5/UEFIPatch_0.3.9_win.zip
  mac: https://github.com/LongSoft/UEFITool/releases/download/0.21.5/UEFIPatch_0.3.9_osx.zip
2. Edit the patches.txt file (included in the zip above) with this content: https://raw.githubusercontent.com/LongSoft/UEFITool/master/UEFIPatch/patches.txt
2. Download the BIOS from ASUS
3. Patch it: 
  win: $ ./UEFIPatch.exe BIOS_FILE
  mac: $ ./UEFIPatch BIOS_FILE

For flashing it, you'll need to use USB BIOS Flashback.

**Comment by danielstuart14** [comment]
Idk if it'll work with Skylake-x / Kabylake-x, but you can try.

**Comment by interferenc** [comment]
I tried it and it doesn't. Interestingly, the KabyLake patch gets applied (KabyLake-X?), but I am using a skylake x, and even when flashed, msr 0xe2 is still locked. Any idea how to proceed?

**Comment by danielstuart14** [comment]
Hmm, I see. Probably the pattern is different.
I'll check your bios. The pattern should start with "0FBA6C24"

**Comment by interferenc** [comment]
There are plenty of those. If you really try to find a patch, thank you in advance.

If I can help in any way, just tell me.

**Comment by interferenc** [comment]
Here is the bios:
https://www.asus.com/us/Motherboards/ROG-STRIX-X299-E-GAMING/HelpDesk_BIOS/

**Comment by danielstuart14** [comment]
I think I see what's going on.
Which processor is yours? (Looking into your bios, there're one Init for each processor. kabylake and skylake)

**Comment by interferenc** [comment]
Skylake-X 7820x

**Comment by danielstuart14** [comment]
Try adding this line to your patches.txt (I recommend using a BIOS file with any patch, at least for now):
D71C8BA4-4AF2-4D0D-B1BA-F2409F0C20D3 10 P:81E10080000033C1:9090909090909090
D71C8BA4-4AF2-4D0D-B1BA-F2409F0C20D3 12 P:81E10080000033C1:9090909090909090

**Comment by danielstuart14** [comment]
x299 in the right and z270 in the left:
![patch](https://i.imgur.com/T72YTgu.png)

**Comment by interferenc** [comment]
First of all, thank you.

Secondly, what do you mean by using a bios file? I am planning on patching the bios .CAP file and then flashing it via flashback. Is that okay?

**Comment by danielstuart14** [comment]
Yeah, that it. Just don't use an already patched .cap file

**Comment by interferenc** [comment]
oh, of course. Thank you, I will try this tonight.

**Comment by danielstuart14** [comment]
You're welcome! Just give a hint after you done that, so we can make a PR. 🍻

**Comment by interferenc** [comment]
Just one question: is it okay if both patches are applied? KabyLake (as before) and now Skylake? Or do I have to create a patches.txt with only this patch?

**Comment by danielstuart14** [comment]
Maybe, only skylake-x should be enough. But, I'd recommend trying with both patches.
I just did the changes needed, use this: https://raw.githubusercontent.com/danielstuart14/UEFITool/master/UEFIPatch/patches.txt

**Comment by interferenc** [comment]
So I have applied the patches, the output was this:

octa:UEFIPatch_0.3.9_osx interferenc$ ./UEFIPatch ROG-STRIX-X299-E-GAMING-ASUS-0802.CAP
parseImageFile: Aptio capsule signature may become invalid after image modifications
parseFile: non-empty pad-file contents will be destroyed after volume modifications
parseFile: non-empty pad-file contents will be destroyed after volume modifications
patch: replaced 8 bytes at offset 4380h 81E10080000033C1 -> 9090909090909090
patch: replaced 8 bytes at offset 4380h 81E10080000033C1 -> 9090909090909090
patch: replaced 8 bytes at offset 2C8FDh 81E10080000033C1 -> 9090909090909090
patch: replaced 8 bytes at offset 2C8FDh 81E10080000033C1 -> 9090909090909090
Image patched

I renamed the output to X299SE.CAP (as instructed from the manual), and flashed it. The BIOS settings were reset, so it did it.

Upon booting, my MSR 0xE2 still has the value of 0x8400, so bit 15 is still set, so it is still locked.

Any idea why it did not work?

**Comment by danielstuart14** [comment]
Maybe we're missing something. I'll check with IDA later

**Comment by interferenc** [comment]
Thank you, I would really appreciate it. 

I just flashed it again in case I somehow messed up, but same results.

**Comment by interferenc** [comment]
Okay so something strange is happening here. With the Kaby Lake patch applied, if I open the patched .CAP file in UEFITool, there are two TE Image sections under 299D6F8B-2EC9-4E40-9EC6-DDAA7EBF5FD9 with the same size. I am not sure this affects anything, but does not look right.

Also, in the Skylake x part, just above the patched region, there is another 0x8000 in a context I can't understand:

`0002d8e5         or         eax, 0x8000`

Maybe this (and something above/below) should also be nop-ed?

**Comment by interferenc** [comment]
This is the relevant part:

`0002d8d5         cmp        byte [ds:esi+0xf837], 0x4                       
0002d8dc         jae        0x2d8e5
0002d8de         and        eax, 0xffff7fff
0002d8e3         jmp        0x2d8ea
0002d8e5         or         eax, 0x8000`

It is as if it is trying to enforce a lock if something is true, or enforce the lack of a lock if it is false. My best guess is that if both branches would do the

`0002d8de         and        eax, 0xffff7fff`

command, it would be okay. What do you think?

**Comment by interferenc** [comment]
I have tried to create a patch to do the above like this:
`D71C8BA4-4AF2-4D0D-B1BA-F2409F0C20D3 12 P:0D008000008A8EB50E0000:25FF7FFFFF8A8EB50E0000`

But I can not apple two patches in one round, it says `reconstructVolume: root volume can't be grown`

**Comment by interferenc** [comment]
Okay so I went ahead with this and even with both parts patched, I still get 0x8400 as a default value, so MSR 0xE2 is still locked.

**Comment by interferenc** [comment]
Okay so I think the correct patch will be more like the x99 patch.

Here is the part the x99 patch patches from an x99 bios
```
0000000000000f56         mov        ecx, 0xe2
0000000000000f5b         rdmsr      
0000000000000f5d         shl        rdx, 0x20
0000000000000f61         or         rax, rdx
0000000000000f64         mov        qword [ss:rsp-0x0+arg_38], rax
0000000000000f69         bts        dword [ss:rsp-0x0+arg_38], 0xf
0000000000000f6f         mov        rdx, qword [ss:rsp-0x0+arg_38]
0000000000000f74         mov        eax, dword [ss:rsp-0x0+arg_38]
0000000000000f78         shr        rdx, 0x20
0000000000000f7c         wrmsr
```

The patch replaces `bts    DWORD PTR [esp+0x40],0xf` to `btr    DWORD PTR [esp+0x40],0xf`

And here is the part in the x299 bios
```
mov        ecx, 0xe2
000000000000297b         rdmsr      
000000000000297d         shl        rdx, 0x20
0000000000002981         or         rax, rdx
0000000000002984         bt         eax, 0xf
0000000000002988         mov        qword [ss:rsp+0x8], rax
000000000000298d         jb         0x29a2
000000000000298f         bts        eax, 0xf
0000000000002993         mov        dword [ss:rsp+0x8], eax
0000000000002997         mov        rdx, qword [ss:rsp+0x8]
000000000000299c         shr        rdx, 0x20
00000000000029a0         wrmsr
```

**Comment by interferenc** [comment]
So I went ahead again and patched all three patches in three separate rounds, and as a result, MSR 0xE2 is unlocked finally. Still not sure all the patches are needed.

**Comment by anonym323** [comment]
How can we patch this exactly in three rounds please make a full description @interferenc

**Comment by danielstuart14** [comment]
Add this to your patches.txt:
# PpmInitialize | Skylake X 
3FFCAE95-23CF-4967-94F5-16352F68E43B 10 P:0FBAE80F:0FBAE00F

**Comment by danielstuart14** [comment]
@interferenc I think only your patch should work, nice job! I'd recommend trying with only it and if it works, making a PR to the UEFITool git.

**Comment by danielstuart14** [comment]
@anonym323 Change your patches.txt to this: https://raw.githubusercontent.com/danielstuart14/UEFITool/master/UEFIPatch/patches.txt

@interferenc Did you tested only with your patch? Maybe the bios locks MSR 0xE2 in multiple modules, but idk... Anyways, nice job!

**Comment by anonym323** [comment]
atch_0.3.9_osx/PRIME-X299-DELUXE-ASUS-0802.CAP 
parseImageFile: Aptio capsule signature may become invalid after image modifications
parseVolume: unknown file system 5473C07A-3DCB-4DCA-BD6F-1E9689E7349A
parseFile: non-empty pad-file contents will be destroyed after volume modifications
parseFile: non-empty pad-file contents will be destroyed after volume modifications
Function called with invalid parameter

**Comment by anonym323** [comment]
but no new bios file

**Comment by interferenc** [comment]
You should make sure each patch line ends with a trailing space, otherwise you get the "Function called with invalid parameter" error.

I have no idea about parseVolume: unknown file system 5473C07A-3DCB-4DCA-BD6F-1E9689E7349A.

Also, it is entirely possible that different boards/bioses would require different patches.

**Comment by interferenc** [comment]
Okay so I checked and PRIME-X299-DELUXE-ASUS-0802.CAP has a parent volume for 3FFCAE95-23CF-4967-94F5-16352F68E43B called 5473C07A-3DCB-4DCA-BD6F-1E9689E7349A.

It is in the file format ffs v3, and it turns out UEFIPatch can not read that.

**Comment by danielstuart14** [comment]
@interferenc is right. Even with FFSv3 patch (available in the PR section), UEFIPatch still doesn't work. I'd suggest extracting the bodies with UEFITool and editing it with an hex editor.

**Comment by amezin** [comment]
@interferenc probably your last patch alone is enough.

I tried `3FFCAE95-23CF-4967-94F5-16352F68E43B 10 P:72130FBAE80F:66900FBAE00F` (added `jb` -> `nop` to your patch) on prime x299-a bios 1004, and it worked, without any other skylake-x patches. Not sure if `jb` -> `nop` is really necessary (probably not)

**Comment by anonym323** [comment]
Did that also work with the new x299 deluxe bios file?

**Comment by amezin** [comment]
@anonym323 I think the same problem will occur. It patches the file you previously had problems with. If you need a solution - you could try what @danielstuart14 suggests
