### ISSUE TITLE
Asus Z8PS-D12-1U bios

### ISSUE THREAD

**Issue by jag9906** [danielstuart14/ASUS_BIOS_REPO#13]
Hello,

I am hoping to get an updated modded bios for my Asus RS700-E6/ERS4 system with asus motherboard Z8PS-D12-1U. I updated yesterday to the 1303 bios the most current its a dual xeon 1366 motherboard bios i used can be found here. https://www.asus.com/Commercial-Servers-Workstations/RS700E6ERS4/HelpDesk_BIOS/

Thanks

**Comment by danielstuart14** [comment]
Sorry, but your AMI version isn't supported by UBU.
