### ISSUE TITLE
ASUS P8Z77V-Pro

### ISSUE THREAD

**Issue by Gregg-Williams** [danielstuart14/ASUS_BIOS_REPO#14]
Hi Daniel,

Would it be possible for you to mod the bios for the P8Z77V-Pro so that it has NVMe support? I've downloaded the present bios from the repository and may try to mod it myself though I have a fear of bricking the bios as I have had that happen to me a long time ago. It's a costly mistake. Thanks.

**Comment by danielstuart14** [comment]
Addressed
