### ISSUE TITLE
p8z77-id

### ISSUE THREAD

**Issue by kroncke-w** [danielstuart14/ASUS_BIOS_REPO#16]
hi, just tried to flash from last asus release to yours, i get a security validation error. what am i doing wrong?

**Comment by kroncke-w** [comment]
Cancel my last. would not update from bios. did update using the AI Suite II. I noted hash codes of your and asus files are different tho the basic & advanced entries appear to be the same, so i feel safe assuming the notec microcode & other changes are in there.

**Comment by danielstuart14** [comment]
Solved then?

**Comment by kroncke-w** [comment]
Yup, All OK so far...
