### ISSUE TITLE
Spectre/Meltdown fixes?

### ISSUE THREAD

**Issue by bykidi** [danielstuart14/ASUS_BIOS_REPO#17]
Topic name.
Is there a newer microcode to fix the these two on our old boards?

**Comment by danielstuart14** [comment]
Seems like intel has released new microcodes for linux, I'll search if we can use that with UBU

**Comment by bykidi** [comment]
P8Z77-V PRO here, ready to test if needed

**Comment by danielstuart14** [comment]
Intel released spectre/meltdown fixes this month. I'll look into updating all the bioses

**Comment by flipphos** [comment]
That would be very nice!
Looking forward to that. And thanks in advance!

**Comment by Metrac** [comment]
WOW, that would be great, thanks! @danielstuart14

**Comment by bykidi** [comment]
@danielstuart14 any news?

**Comment by Korgan75** [comment]
Thanks! Looking forward to this.

**Comment by danielstuart14** [comment]
sorry by the huge delay! College got all my spare time.
All the microcodes were updated, I'd ask if someone can test it.
