### ISSUE TITLE
Asus G20AJ

### ISSUE THREAD

**Issue by julianostarek** [danielstuart14/ASUS_BIOS_REPO#2]
How can I flash this on the G20Aj which doesn't have flashback? And does this have any bad side effects?

**Comment by danielstuart14** [comment]
you can use afudos: http://www.ami.com/support/downloads/amiflash.zip

Also, about bad sides, the only one I can see, is that you won't be able to run it with a broadwell processor.

**Comment by julianostarek** [comment]
@danielstuart14 18 - Error: Unable to start a Secure flash session

**Comment by danielstuart14** [comment]
http://www.win-raid.com/t455f16-Guide-How-to-flash-a-modded-ASUS-ASRock-Gigabyte-AMI-UEFI-BIOS.html

**Comment by julianostarek** [comment]
@danielstuart14 I still get an error trying to use /GAN but the cmd window disappears before I can read it...
