### ISSUE TITLE
Nvme support

### ISSUE THREAD

**Issue by brimur** [danielstuart14/ASUS_BIOS_REPO#3]
Hi, not really an issue, just wondering if NVMe support is included in the Z77-V Deluxe as descibed here...
http://www.win-raid.com/t871f13-Discussion-NVMe-BIOS-Modules-and-NVMe-Support-7.html#msg17072

Thanks

**Comment by danielstuart14** [comment]
it is not, but I'll try add this feature in the advanced bios.
