### ISSUE TITLE
P8Z77-I Deluxe/WD flash issue

### ISSUE THREAD

**Issue by KarateOC** [danielstuart14/ASUS_BIOS_REPO#4]
I have found that the custom "P8Z77-I Deluxe" BIOS cannot be used to flash a "P8Z77-I Deluxe/WD" despite being almost identical boards. I tried to rename the file to Z77IDWD.CAP, which is the usb flashback filename for the WD model, but no luck. I would greatly appreciate if you could also make a custom BIOS for the P8Z77-I Deluxe/WD as well. The latest BIOS for the WD can be found from the link below.
https://www.asus.com/Motherboards/P8Z77I_DELUXEWD/HelpDesk_Download/

**Comment by Vesperus** [comment]
I second the request for this. If there's anyone who would be so kind as to offer it, the favour would be appreciated.
I've also been hunting to find the P8Z77-I Deluxe/WD patched BIOS, with no luck so far. I saw a couple of requests for it, but no follow-up. Were you able to find it, KarateOC?
I couldn't even find the UEFIpatch tool to do it myself, as its repository has been removed from Github.

**Comment by danielstuart14** [comment]
Wow, almost one year. Sorry!
Do you still have this board? I'll close the "issue", but, if needed, just reply and I'll upload a modded version.
