### ISSUE TITLE
N61Da BIOS mod

### ISSUE THREAD

**Issue by Spork-Schivago** [danielstuart14/ASUS_BIOS_REPO#5]
Hello,

Any way you could mod an an Asus N61Da BIOS?   The latest version (209) can be found on Asus's download site http://dlcdnet.asus.com/pub/ASUS/nb/N61DA/N61Daas209.zip?_ga=1.138356345.836819500.1462546995

It'd be nice if there were hidden menu's that could be unlocked.   We'd like to be able to set the RAM timing, for example.   Thanks!

**Comment by danielstuart14** [comment]
Laptops will not be supported, sorry.

**Comment by Spork-Schivago** [comment]
Thanks!
