### ISSUE TITLE
Will these work with Windows OS?

### ISSUE THREAD

**Issue by ireun** [danielstuart14/ASUS_BIOS_REPO#8]
Hello, this is probably really silly question but I wqouldn't want to screw anything up. I'm worried about "MSR 0xE2 Unlocked (Apple PM Fix)" as this is obviously a feature for Hackintosh'es.. Could you explain that to me if this will work with Windows? 10?

**Comment by danielstuart14** [comment]
Yeah, it works fine with windows.
It's a "security" feature for blocking the writing in certain MSR blocks

**Comment by ireun** [comment]
Thanks, I've installed it without any problems, but after booting to BIOS no boot options were visible, I thought that they were wiped out, so I ran Bootrec.exe from command line accessed using Windows 10 USB, they were still not there..

Actually these drives were not available in SATA devices, they were connected to Asmedia 6.0Gb/s, I've connected them to Intel 6Ghz and they started working as expected. Not a big deal, but it you could fix that, that would be good. 

I'm using Asus P8Z77-V with i5 2500K

Thanks. ;)
