### ISSUE TITLE
Z97-Pro Gamer

### ISSUE THREAD

**Issue by shaneret** [danielstuart14/ASUS_BIOS_REPO#9]
Could you look into building a modded BIOS for Z97-Pro gamer v.2203 ?
 thankyou.

**Comment by danielstuart14** [comment]
Yes, I'm going to upload it in the next few hours.

**Comment by danielstuart14** [comment]
Added
https://github.com/danielstuart14/ASUS_BIOS_REPO/blob/master/LGA%201150/z97PROG.CAP
